### ISSUE TITLE
[PROPOSAL] multi-platform prebuilt libraries

### ISSUE THREAD

**Issue by PaTiToMaSteR** [mozilla-spidermonkey/spidermonkey-embedding-examples#67]
SpiderMonkey is getting wide attention these days by the result of the hard development of exceptional people. However is a huge pain in the ass the process to build, test and develop with it. In our case I'm deciding these days which scripting language to attach to our UE5 game and other company projects. 

1. Do you have like github actions or mercurial releases done for multiplatform purposes where we can grab the libs?
2. Is there any interest of keep a SpiderMonkey release track in embedded mode for multi-platform targets?

Thanks in advance!

**Comment by ptomato** [comment]
You can try looking on Mozilla's Treeherder service for CI-built artifacts. For example, https://treeherder.mozilla.org/jobs?repo=mozilla-esr102&searchStr=pkg&selectedTaskRun=EtBqsDEaSRC7txGCvk5ZjQ.0 has a libmozjs-102.so.

Otherwise I think this is probably not the right issue tracker to raise this. I'd suggest trying on Mozilla's issue tracker bugzilla.mozilla.org or inquiring in [#spidermonkey:mozilla.org](https://matrix.to/#/#spidermonkey:mozilla.org). My understanding, which may be out of date, is that Mozilla would be in favour of a release process which would make it easier for embedders to get regular releases of official sources, but it's not a priority right now. I'm not sure about binaries.
