### ISSUE TITLE
faulty installation instructions

### ISSUE THREAD

**Issue by aaaddd4747** [mozilla-spidermonkey/spidermonkey-embedding-examples#76]
i was following along with the installation instructions [listed here](https://github.com/mozilla-spidermonkey/spidermonkey-embedding-examples/blob/esr115/docs/Building%20SpiderMonkey.md), starting from scratch on a fresh system. 
however, when it got time to follow along with the command
```
cp ./configure.in ./configure
```
i am greeted with a lovely
```
cp: cannot stat './configure.in': No such file or directory
```
which, naturally dooms the entire following configuration steps to failure. i have searched the entire source tree for any sort of 'configure.in' and found nothing. why do the installation instructions refer to a file that doesn't exist?

i have tried this with both firefox source ver 120.0, as well as the linked version on the page.
the result is the same in both cases.

additionally, the instructions mention that you can change the installation directory, but neglect to state how to do that. i do need to do this in my case, so fixes and adding sufficient information onto this document would be much appreciated.

**Comment by ptomato** [comment]
I guess this never got updated after https://bugzilla.mozilla.org/show_bug.cgi?id=1787977 which replaced configure.in with configure.

The instructions do say how to change the installation directory ("Add `--prefix=/my/prefix` (where /my/prefix is your chosen prefix) to the configure line if you chose a different prefix.") but reading over it with fresh eyes, I see we didn't make the "prefix" jargon very clear! "Prefix" is what configure calls "installation directory".

Thanks for the feedback! A report from someone starting from scratch is always the most valuable kind because we get to learn what assumptions we're making. I'll fix both of these things.
